### ISSUE TITLE
Export Release Build Problem

### ISSUE THREAD

**Issue by andtankian** [flashapi/hummingbird#2]
I've been working in an AS3 Mobile Application Hummingbird MVC based on. It occurred very well while I didn't export the release build. I've searched on Internet and have not found anything about. Well, How can my application runs perfectly fine in debug/run mode and not even appears in release build mode?
I've tried start again with a simple HelloWorld. Nothing. It seems something with MVC Objects injection, because the HummingbirdAS.setApplicationContext(new AppContext(), stage) API is working great. (I forced it to show something on the screen and BAM!)
The problem is ocurring when start() method into AppContext class invokes any method into any injected MVC objects as: appController.initApp().
The strange is that in debug/run mode everything runs OK! Only in the release build mode that, apparently, it can't creat an instance of the Controller (or another mvc objects live model, services, etc).

Can anyone help?

**Comment by flashapi** [comment]
You must declare metada to compiler, as explained in the following tutorial :
[Get Started With Hummingbird](http://flashapi.org/hummingbird/get-started-with-hummingbird/)
